### PR TITLE
use babel parser

### PR DESCRIPTION
**Pull request by hzoo**
WIP: Lots of failling tests.

At first I just did `import {parse} from 'babel-core';` but then it would all be acorn stuff so I figured the 'parser' in babel-jscs could work to convert using `acorn-to-esprima` - https://github.com/jscs-dev/babel-jscs/blob/53cb7bdaa0e80d106f2384e2d9ecc8a1715e2b31/index.js#L88-L135

There's probably a few issues to fix here. Probably want to move `acorn-to-esprima` to new repo too. https://github.com/babel/babel-eslint/issues/24

### CODE REVIEW

**Comment by mdevils** [comment]
Wow, some errors are very bad. For instance:

```
SyntaxError: Line X: You're trying to assign to a parenthesized expression, eg. instead of `({a}) = 0` use `({a} = 0)`
```

Looks like acorn does not support this part of JavaScript: `(x) = 1`

**Comment by mdevils** [comment]
How do you think, is it possible to fix this kind of errors?

```
 4) Literal should accept single quoted string:
      AssertionError: expected '"123"' to equal '\'123\''
      + expected - actual
      -"123"
      +'123'
```

For me it looks like `Acorn` does not store initial string quotes.

**Comment by hzoo** [comment]
There's a few options we can use like a nonstrict mode?

I'm not sure but I think the single quote thing could be similar to https://github.com/jscs-dev/babel-jscs/issues/1

**Comment by hzoo** [comment]
So

```js
var tree = parse(code);
console.log(tree.body[0].expression.raw); // node.raw == '\'123\''
```

At this line
`children.push(new Token(token.type, token.value));`
`token.value = '"123"'` because the ast.tokens from babel doesn't contain quotes (but the tree has it). So it's the same issue for jscs
https://github.com/mdevils/cst/blob/master/lib/elementTree.js#L155

**Comment by mdevils** [comment]
> There's a few options we can use like a nonstrict mode?

What does that nonstrict mode mean? From ECMAScript point of view?

> I'm not sure but I think the single quote thing could be similar to jscs-dev/babel-jscs#1 (It does store the string quotes in the ast.tree but it's getting transformed or something (also ast.tokens doesn't store the initial string quotes)

Yes, it is the same issue. The problem is that `babel`'s token list does not have raw values, but should have...

**Comment by hzoo** [comment]
Yeah since I think it's strict mode by default no all the with tests will fail

**Comment by mdevils** [comment]
But again: why `(x) = 1` does not work in `babel` strict mode. What is that strict mode about? In JS strict mode `(x) = 1;` is allowed.

**Comment by hzoo** [comment]
I don't know if that specific issue is related to strict mode (I was talking about the other errors like with `with`)

**Comment by mdevils** [comment]
@hzoo oh, I understand. Yes, `with` does not conform strict mode.

**Comment by hzoo** [comment]
Ok looks like `({x}) = 1` is illegal but `(x) = 1` isn't 
https://github.com/babel/babel/commit/c2da77d7ec146795ada6d73d20bcbef4cd48db3a

**Comment by mdevils** [comment]
But actually you can run `(x) = 1;` in all JS engines and it will work. I tested in `node`, `Chrome`, `Firefox`, `Safari`, `Opera` (Presto).

**Comment by hzoo** [comment]
No you're right I said
> Ok looks like `({x}) = 1` is illegal but `(x) = 1` isn't

The tests that are failing are `({x}) = 1`

**Comment by mdevils** [comment]
Ah, I see what you mean. OK.

**Comment by mdevils** [comment]
So some of the tests should be dropped.

**Comment by hzoo** [comment]
Or you can change the test to be `({a} = 0)` if possible

**Comment by mdevils** [comment]
Yes, good idea.

**Comment by hzoo** [comment]
Could try to modify parse so that it would take options (so you can pass in `strict: false` for the with tests) or something but not sure.

**Comment by hzoo** [comment]
Ok I just did the simplest thing to support non-strict/loose mode by changing `babel-jscs` to accept another parameter to change strictMode to false or true.

Probably not the best way (creating more methods) but can change later

**Comment by mdevils** [comment]
> Although actually - I don't know how you would support with without having to specify if the user is using es6 or not right.

I think there should be possible to specify ES version when configuring parser (+features like JSX in future).

**Comment by mdevils** [comment]
> numeric literals (octal, etc)

It's the same problem as we have with string.

**Comment by hzoo** [comment]
Do you whats up with this issue?

```js
8) TryStatement should accept catch statement:
     Error: Expected token value "finally" but catch found
      at ElementAssert.assertToken (lib/elements/ElementAssert.js:60:23)
```

**Comment by mdevils** [comment]
Probably here is the answer: https://github.com/mdevils/cst/blob/master/lib/elementTree.js#L72

**Comment by hzoo** [comment]
Ok you're right - I just added `handler` and it worked

https://github.com/babel/babel/blob/master/src/babel/types/visitor-keys.json#L64

**Comment by hzoo** [comment]
Is there a way to get the quote value from the ast tree since the tokens array doesn't have it, or do some kind of mapping? Not sure what we can do there

**Comment by hzoo** [comment]
@mdevils Should I try to fix the quotes stuff or are you going to later?

**Comment by mdevils** [comment]
@hzoo if you have time, fix please, I'm working on the Element structure right now.

**Comment by hzoo** [comment]
So how do I read the source given the node.loc or node.range to get the quotes?

**Comment by mdevils** [comment]
`token.value = source.slice(token.range[0], token.range[1]);`

It can actually be done in `babel-jscs` package

**Comment by hzoo** [comment]
Ok I had to change it a bit to pass the source but it looks like it works!

**Comment by mdevils** [comment]
Great news! Can't wait to do some benchmarks :)

**Comment by hzoo** [comment]
Ok great yeah all those tests pass.

The last 2 errors are related to strict mode - should I run those 2 tests in non-strict mode too, or we remove with from that test?

**Comment by mdevils** [comment]
Non-strict is OK for now. Let's have with-tests for now.

**Comment by mdevils** [comment]
(I don't mean always non-strict, only for those test as you did it before).

**Comment by hzoo** [comment]
Yay tests passed - look through the diff one more time though

**Comment by mdevils** [comment]
Diff looks good. Can I merge?

**Comment by hzoo** [comment]
OK I'm OK with merging other than if you want to change how the strict/non
strict methods are used (extra param).

**Comment by hzoo** [comment]
https://github.com/jscs-dev/babel-jscs/blob/master/index.js#L88-L99

**Comment by mdevils** [comment]
I will add separate method for non-strict mode later. Thank you!

**Comment by hzoo** [comment]
ctrl+f through the code - there's a few other esprima-fb things - actually we could use babel-jscs instead of esprima-fb so can remove from dependencies or actually might need to move babel-jscs to be a dependency.

**Comment by mdevils** [comment]
Extremely bad news, @hzoo. Take a look on benchmarks.

`npm run test:benchmark`

Using esprima:

```
CST building costs
   - Parse (esprima) x 10.84 ops/sec ±9.32% (32 runs sampled)
   - Parse, fix tokens x 10.86 ops/sec ±6.90% (31 runs sampled)
   - Parse, fix tokens, build CST x 3.76 ops/sec ±10.88% (14 runs sampled)
```

Using babel-jscs:

```
CST building costs
   - Parse (babel) x 2.23 ops/sec ±5.39% (10 runs sampled)
   - Parse, fix tokens x 2.17 ops/sec ±8.33% (10 runs sampled)
   - Parse, fix tokens, build CST x 1.53 ops/sec ±11.28% (8 runs sampled)
```

**Comment by hzoo** [comment]
Hmm yeah that's way slower. Acorn itself isn't going to be that much slower than esprima though

```js
// on my slower computer
// this PR
CST building costs
   - Parse (babel) x 1.24 ops/sec ±8.65% (8 runs sampled)
   - Parse, fix tokens x 1.38 ops/sec ±1.39% (8 runs sampled)
   - Parse, fix tokens, build CST x 0.61 ops/sec ±9.94% (6 runs sampled)
  Fastest is Parse, fix tokens


// before PR
CST building costs
 - Parse (esprima) x 3.00 ops/sec ±10.99% (12 runs sampled)
 - Parse, fix tokens x 3.24 ops/sec ±5.74% (13 runs sampled)
 - Parse, fix tokens, build CST x 1.10 ops/sec ±7.87% (7 runs sampled)
Fastest is Parse, fix tokens,Parse (esprima)
```

**Comment by mdevils** [comment]
I will try to investigate the issue.

**Comment by hzoo** [comment]
I just tried `import {parse} from 'babel-core';` and got `Parse x 3.66 ops/sec ±2.73% (13 runs sampled)
`
Of course getting errors building since it would fail all the test but it's fast.

**Comment by mdevils** [comment]
Created a branch with a fix: https://github.com/mdevils/cst/blob/mdevils/faster-parse/lib/elementTree.js#L242

I used `toToken` function from `babel-jscs`. Looks like we don't need most of `babel-jscs` here. Instead of emulating `esprima` behaviour, we can just use advantages of `acorn`. For instance, `start/end` fields, disabling `range` and `loc` generation.

Results are very close to `esprima`'s:

```
CST building costs
   - Parse (esprima) x 9.79 ops/sec ±5.93% (28 runs sampled)
   - Parse, fix tokens x 9.87 ops/sec ±2.30% (29 runs sampled)
   - Parse, fix tokens, build CST x 3.61 ops/sec ±9.54% (14 runs sampled)
  Fastest is Parse, fix tokens,Parse (esprima)
```

**Comment by hzoo** [comment]
Oh nice!

Yeah don't need the monkeypatch method for estraverse since that's only for jscs.

Not sure if we need https://github.com/jscs-dev/babel-jscs/blob/master/acorn-to-esprima.js#L68

We will probably need 
https://github.com/jscs-dev/babel-jscs/blob/master/acorn-to-esprima.js#L73 when template strings are added (I just hacked that together so probably not performant either)

**Comment by mdevils** [comment]
I think we can just adopt `toToken` from `acorn-to-esprima` and this will be enough. No more tranformations needed.

**Comment by hzoo** [comment]
Yeah it sounds like it is working well

**Comment by hzoo** [comment]
@sebmck is going to move that part into its own package

**Comment by mdevils** [comment]
Oh, then we can go like this now and then use his package.

**Comment by mdevils** [comment]
Merged to master.

**Comment by mdevils** [comment]
Added you to contributor list.

**Pull request merged**
